import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, rm, readFile, writeFile, cp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from 'node:http';
import { chromium } from 'playwright';
import { PDFDocument, PDFName, PDFDict, PDFArray, PDFRawStream } from 'pdf-lib';
import JSZip from 'jszip';
import { startApp } from '../src/interfaces/http/server.ts';

const root=await mkdtemp(path.join(tmpdir(),'freyja-browser-')),app=await startApp(root);
const browser=await chromium.launch({executablePath:process.env.FREYJA_BROWSER});
let staticServer: ReturnType<typeof createServer> | undefined;
try {
  const created=await app.service.create({id:'browser-talk',title:'How retries recover'});
  const base=await app.preview(created.id), page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${base}#/recovery/0`);
  await page.waitForSelector('.reveal.ready');
  await page.mouse.move(720,300);
  assert.equal(await page.locator('.f-controls').evaluate(e=>getComputedStyle(e).opacity),'0','Controls stay hidden away from the bottom edge');
  await page.mouse.move(720,880);
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.f-controls')!).opacity==='1');
  await readFile(path.join(root,'vite',created.id,'deps','_metadata.json'));// each preview owns its dependency cache
  const position=async(id:string,step:number)=>page.waitForFunction(([id,step])=>window.freyja?.position.slideId===id&&window.freyja.position.step===step,[id,step]);
  await position('recovery',0);
  for(let i=1;i<=3;i++){await page.keyboard.press('ArrowRight');await position('recovery',i);}
  assert.equal(await page.locator('.present .f-metric strong').first().textContent(),'1');
  const panelBox=await page.locator('.present .f-state-panel').boundingBox();
  const footerBox=await page.locator('.present .f-footer').boundingBox();
  assert.ok(panelBox&&footerBox&&panelBox.y+panelBox.height<=footerBox.y,'Starter flow state must fit above its footer');
  await page.keyboard.press('ArrowLeft');await position('recovery',2);
  await page.getByRole('button',{name:'Saved',exact:true}).click();await position('recovery',1);
  await page.keyboard.press('ArrowRight');await position('recovery',2);
  await page.keyboard.press('g');await page.getByRole('textbox',{name:'Search slides'}).fill('conversation');
  await page.getByRole('button',{name:/A conversation that leads/}).click();await position('demo',0);
  assert.equal(await page.locator('.present .demo-layout').evaluate(e=>e.classList.contains('has-results')),false);
  await page.keyboard.press('ArrowRight');await position('demo',1);
  assert.equal(await page.locator('.present .demo-layout').evaluate(e=>e.classList.contains('has-results')),true);
  await page.reload();await page.waitForSelector('.reveal.ready');await position('demo',1);
  await page.keyboard.press('o');assert.ok(await page.getByRole('dialog',{name:'Slide overview'}).isVisible());await page.keyboard.press('Escape');
  await app.operations.open_presentation({id:created.id,slideId:'decisions',step:2});await position('decisions',2);
  const screenshot=await app.operations.render_slide({id:created.id,slideId:'recovery',step:3}) as {path:string};
  assert.ok((await readFile(screenshot.path)).length>10000);await position('decisions',2);
  const beforeExport=await app.operations.get_presentation_state({id:created.id}) as {position:unknown};
  const finalPdf=await app.operations.export_pdf({id:created.id}) as {path:string;pages:number;mode:string};
  const manifest=JSON.parse(await readFile(path.join(created.source,'deck.json'),'utf8'));
  const printed=await PDFDocument.load(await readFile(finalPdf.path));
  assert.equal(finalPdf.pages,manifest.slides.length);assert.equal(finalPdf.mode,'final');
  assert.equal(printed.getPageCount(),manifest.slides.length);
  const pageFingerprints:string[]=[];
  for(const sheet of printed.getPages()) {
    const contents=sheet.node.Contents();assert.ok(contents);
    const streams=contents instanceof PDFArray ? contents.asArray().map(ref=>{const stream=printed.context.lookup(ref);assert.ok(stream instanceof PDFRawStream);return stream;}) : [contents];
    const hash=createHash('sha256');for(const stream of streams)hash.update(stream.getContents());
    pageFingerprints.push(hash.digest('hex'));
    assert.equal(sheet.getWidth(),960);assert.equal(sheet.getHeight(),540);
    const fonts=sheet.node.Resources()?.lookupMaybe(PDFName.of('Font'),PDFDict);
    assert.ok(fonts&&fonts.keys().length>0,'Export must retain PDF text fonts rather than rasterizing each slide');
  }
  assert.equal(new Set(pageFingerprints).size,manifest.slides.length,'Each PDF page must contain its own rendered slide');
  const allPdf=await app.operations.export_pdf({id:created.id,allSteps:true}) as {path:string;pages:number};
  const expectedSteps=manifest.slides.reduce((count:number,slide:{steps:string[]})=>count+slide.steps.length,0);
  assert.equal(allPdf.pages,expectedSteps);
  assert.equal((await PDFDocument.load(await readFile(allPdf.path))).getPageCount(),expectedSteps);
  assert.deepEqual((await app.operations.get_presentation_state({id:created.id}) as {position:unknown}).position,beforeExport.position);
  await position('decisions',2);
  const pptx=await app.operations.export_pptx({id:created.id}) as {path:string;slides:number;mode:string};
  assert.equal(pptx.slides,manifest.slides.length);assert.equal(pptx.mode,'final');
  const deckZip=await JSZip.loadAsync(await readFile(pptx.path));
  const slideXml=Object.keys(deckZip.files).filter(f=>/^ppt\/slides\/slide\d+\.xml$/.test(f));
  assert.equal(slideXml.length,manifest.slides.length,'One PowerPoint slide per deck slide');
  const media=Object.keys(deckZip.files).filter(f=>f.startsWith('ppt/media/')&&!f.endsWith('/'));
  assert.equal(media.length,manifest.slides.length,'Each PowerPoint slide carries its rendered image');
  const firstImage=await deckZip.file(media[0])!.async('nodebuffer');
  assert.equal(firstImage.readUInt32BE(16),2560,'Slides render at 2x width');
  assert.match(await deckZip.file('ppt/slides/slide1.xml')!.async('string'),new RegExp(manifest.slides[0].title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  assert.doesNotMatch(await deckZip.file('ppt/slides/slide2.xml')!.async('string'),/p:transition/,'Decks without transitions export none');
  const allPptx=await app.operations.export_pptx({id:created.id,allSteps:true}) as {slides:number;path:string};
  assert.equal(allPptx.slides,expectedSteps);
  const allZip=await JSZip.loadAsync(await readFile(allPptx.path));
  assert.match(await allZip.file('ppt/slides/slide3.xml')!.async('string'),/<p:transition spd="fast">/,'Further steps of a slide fade quickly');

  const rejectedPdf=await fetch(`${app.url}/api/pdf/${created.id}`,{method:'POST',headers:{Origin:'https://foreign.example','Content-Type':'application/json'},body:'{}'});
  assert.equal(rejectedPdf.status,403);
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export PDF',exact:true}).click();
  const download=await downloadEvent,downloadPath=await download.path();assert.ok(downloadPath);
  assert.equal(download.suggestedFilename(),`${created.id}.pdf`);
  assert.equal((await PDFDocument.load(await readFile(downloadPath))).getPageCount(),manifest.slides.length);
  await page.getByRole('button',{name:'Export PDF',exact:true}).waitFor();await position('decisions',2);
  const pptxDownloadEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export PPTX',exact:true}).click();
  const pptxDownload=await pptxDownloadEvent;assert.equal(pptxDownload.suggestedFilename(),`${created.id}.pptx`);
  await page.getByRole('button',{name:'Export PPTX',exact:true}).waitFor();await position('decisions',2);
  // Ordinary source editing must become visible through Vite.
  const intro=path.join(created.source,'slides/intro.tsx'),code=await readFile(intro,'utf8');
  await writeFile(intro,code.replace('{slide.title}','Source edited directly'));
  await app.operations.open_presentation({id:created.id,slideId:'intro',step:0});
  await page.getByRole('heading',{name:'Source edited directly'}).waitFor();
  const brandFile=path.join(created.source,'brand.json'),brand=JSON.parse(await readFile(brandFile,'utf8'));
  brand.colors.accent='#8844cc';await writeFile(brandFile,JSON.stringify(brand));
  await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent')==='#8844cc');
  const validated=await app.service.validate(created.id);assert.equal(validated.ok,true,JSON.stringify(validated));
  const built=await app.service.build(created.id);
  staticServer=createServer(async(req,res)=>{try{const file=path.join(built.output,(req.url??'/').split('?')[0]==='/'?'index.html':(req.url??'/').slice(1));const mime=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html';res.writeHead(200,{'Content-Type':mime});res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});
  await new Promise<void>(resolve=>staticServer!.listen(0,'127.0.0.1',resolve));const address=staticServer.address();assert.ok(address&&typeof address!=='string');
  const exported=await browser.newPage();await exported.goto(`http://127.0.0.1:${address.port}/#/recovery/2`);await exported.waitForSelector('.reveal.ready');
  await exported.waitForFunction(()=>window.freyja?.position.step===2);assert.equal(await exported.locator('.present .f-flow-node').first().textContent(),'WorkerReply lost');
  assert.equal(await exported.getByRole('button',{name:'Export PDF',exact:true}).count(),0);assert.equal(await exported.getByRole('button',{name:'Export PPTX',exact:true}).count(),0);
  await exported.keyboard.press('ArrowRight');await exported.waitForFunction(()=>window.freyja?.position.step===3);
  const midnight=await app.service.create({id:'another-topic',title:'Another topic',theme:'midnight'});
  const dark=await browser.newPage();await dark.goto(await app.preview(midnight.id));await dark.waitForSelector('.reveal.ready');
  assert.equal(await dark.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--background')),'#101629');
  const profileDir=path.join(root,'repo/profile');await cp(path.join(import.meta.dirname,'fixtures/profile'),profileDir,{recursive:true});
  const profiled=await app.service.create({id:'profile-talk',title:'Profiled talk',directory:path.join(root,'repo/decks/profile-talk'),profile:profileDir});
  const branded=await browser.newPage();const brandErrors:string[]=[];branded.on('pageerror',e=>brandErrors.push(e.message));
  await branded.goto(await app.preview(profiled.id));await branded.waitForSelector('.reveal.ready');
  assert.equal(await branded.locator('.present .fixture-badge').textContent(),'Profiled talk');
  assert.equal(await branded.locator('.present .fixture-badge svg').count(),1,'Profile components can import lucide-react icons');
  assert.equal(await branded.locator('.present .fixture-badge').evaluate(e=>getComputedStyle(e).color),'rgb(255, 0, 170)','Brand tokens and profile styles must reach @profile components');
  assert.equal(await branded.locator('.present .f-canvas').evaluate(e=>e.getAttribute('data-variant')),'inverse');
  assert.equal(await branded.locator('.present .f-canvas').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(17, 17, 17)');
  assert.ok((await readFile((await app.operations.render_slide({id:profiled.id,slideId:'intro',step:0}) as {path:string}).path)).length>5000);
  const profiledBuild=await app.service.build(profiled.id);assert.ok((await readFile(profiledBuild.entry,'utf8')).includes('<div id="root">'));
  assert.equal(await branded.locator('.reveal .slides > section').first().getAttribute('data-transition'),'fade','The deck transition reaches Reveal');
  const profiledPptx=await app.operations.export_pptx({id:profiled.id}) as {path:string};
  assert.match(await (await JSZip.loadAsync(await readFile(profiledPptx.path))).file('ppt/slides/slide1.xml')!.async('string'),/<p:transition spd="med"><p:fade\/><\/p:transition>/,'The same transition reaches PowerPoint');
  assert.deepEqual(brandErrors,[]);
  assert.deepEqual(errors,[]);assert.equal(await page.locator('[role=alert]').count(),0);
  console.log('Browser checks passed: reverse, tabs, jump, overview, deep links, MCP navigation, isolated capture, source/theme refresh, static build, second theme, profile styles/tokens/variants/kit imports, PDF final/all-step exports and PPTX image exports with deck transitions and isolated downloads.');
}finally{await browser.close();if(staticServer)await new Promise<void>(resolve=>staticServer!.close(()=>resolve()));await app.close();await rm(root,{recursive:true,force:true});}
